source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mongoid', '~> 3.0.5'
gem 'heroku'
gem 'jquery-rails'
gem 'devise', '~> 2.1.2'
gem 'thin'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end



group :development do
  gem 'sextant' 
  gem 'quiet_assets'
  gem 'guard', '>= 0.6.2'
  gem 'rb-fsevent'
  gem 'growl'
  gem 'guard-bundler', '>= 0.1.3'
  gem 'guard-rails', '>= 0.0.3'
  gem 'guard-livereload', '>= 0.3.0'
  gem 'guard-rspec', '>= 0.4.3'
  gem 'guard-spork'
  gem 'spork', '~> 1.0rc'
  gem 'pry-rails'
  gem 'rspec-nc'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'quiet_assets'
  gem 'debugger'
end


group :test do
  gem "database_cleaner", ">= 0.7.0"
  gem "factory_girl_rails", ">= 1.4.0"
  gem "capybara", ">= 1.1.2"
  gem "email_spec"
  gem 'simplecov'
  gem 'faker'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
